### ISSUE TITLE
its not possible to define extra args

### ISSUE THREAD

**Issue by abendt** [tmullender/ansible-maven-plugin#11]
would be useful to be able to define extra args to the execution
e.g. "-v" etc

**Comment by tmullender** [comment]
Hi Alphonse

Which goal are you using? For ansible-playbook this should be possible. There is an example in https://github.com/tmullender/ansible-maven-plugin/blob/master/src/it/extra-vars-ansible-playbook/pom.xml

Does that help? 

Tim

**Comment by abendt** [comment]
Hey Tim,

i'm using the playbook goal
the extraVars config options issues the option -e. this is not want i need.
i want to add -vvv for a more verbose output.

so there could be either a verbose configuration option or a more generic extraArgs configuration option?

Alphonse

**Comment by tmullender** [comment]
Sorry Alphonse, I misread what you'd written, extra options should be possible but don't appear to be documented. I can check later when I have my laptop but you can see an example at https://github.com/tmullender/ansible-maven-plugin/blob/master/src/it/extra-options-ansible/pom.xml

**Comment by tmullender** [comment]
I've double checked the following works within the configuration section of the playbook goal
```
              <options>
                <option>-vvv</option>
              </options>
```

Does this work for you?

**Comment by abendt** [comment]
Hi Tim,

this works.
thank you!

Alphonse

**Comment by tmullender** [comment]
Documentation updated, closing
